### PR TITLE
Add keyword for loading fixtures into the database

### PR DESCRIPTION
**Pull request by MatthewWilkes**
Hey, so, I did a stupid thing. I had a second checkout that had uncommitted changes.

You might want to treat this more as a WIP, as there aren't any relevant tests, but I wanted to make it visible as you're working on this today.

### CODE REVIEW

**Comment by tisto** [comment]
Ok. I guess we need some tests and docs for that.

**Comment by tisto** [comment]
Hey @MatthewWilkes,

I just added a few new keywords for Postgres support:
- Manage Makemigrations
- Manage Migrate
- Manage Flush

Would you mind if I merge your pull request and rename the keyword to 'Manage Loaddata'? I'd be open for name suggestions if you prefer different conventions. We should just make sure the manage keywords are named in a consistent manner.

**Comment by MatthewWilkes** [comment]
I don't mind at all, just be aware that I'm not really sure it's Good Enough(tm). I'm sadly not using RobotFramework for the current batch of projects (despite having about 50 pages of gherkin BDD specs) so it fell off my radar a little bit.

**Comment by tisto** [comment]
@MatthewWilkes I will close this pull request for now. I implemented a few factory boy keywords for creating test fixture and I don't have time to work on an alternative approach. Feel free to re-open any time if you want to continue to work on this.

**Pull request closed without merging**
