### PR TITLE
Document test database setup

### PR DESCRIPTION
**Pull request by ghost**
When running unit/integration tests with default PostgreSQL settings, you'll get this error:

        $ fe_sendauth: no password supplied
    
This note provides hints about how to configure your system to solve this issue.

This problem doesn't occur with Travis because it's already configured to allow password-less connection as user postgres.

### CODE REVIEW

**Comment by tisto** [comment]
This build shouldn't fail since it does not change anything in the code. Will look into it...

**Comment by tisto** [comment]
@amarandon I am not sure if we should start adding generic recommendations for the db setup. Wouldn't it be better to just link to the postgres docs?

**Comment by ghost** [comment]
@tisto Yes you're probably right.

**Comment by tisto** [comment]
@amarandon ok, closing this for now. Thanks for contributing and your help with the 2.0 release!

**Pull request closed without merging**
